### ISSUE TITLE
Can't use iron_bars

### ISSUE THREAD

**Issue by RoboMWM** [MineSworn/AutoCraft#5]
Tried adding iron_bars in config and it shows up as null in /ac allowed. Tried block id and apparently integers are not allowed in that list (which means devbukkit resource is out of date)

Using build 343

**Comment by dmulloy2** [comment]
Iron bars are actually called IRON_FENCE in Bukkit. AutoCraft pulls from the [Bukkit Material enum](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/Material.java#167).
