### ISSUE TITLE
Cannot pilot with empty hand

### ISSUE THREAD

**Issue by RoboMWM** [MineSworn/AutoCraft#8]
Unless this is intended, it is not possible to pilot a ship with an empty hand. This is likely due to PlayerInteractEvent being automatically canceled in spigot - and can be fixed by listening at a lower priority, iirc.

**Comment by dmulloy2** [comment]
I'm pretty sure I looked into it and the issue was that it's simply never called. Theres not much I can do with AC to fix that. It shouldn't matter if the event is cancelled.

**Comment by RoboMWM** [comment]
Hmm, I guess I must've been remembering that it's canceled only if attempting to interact with an air block. Sorry about that.
